package bg.smg.frames;

import bg.smg.model.Recipe;
import bg.smg.services.RecipeService;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
/**
 *
 * @author smg25C9
 */
public class RecipePreviewPanel extends javax.swing.JPanel {

    Recipe currentRecipe;
    RecipeService recipeService = new RecipeService();
    /**
     * Creates new form RecipePreviewPanel
     */
    public RecipePreviewPanel() {
        initComponents();
        jLabelRecipePreviewImg.setIcon(null);
        jLabel1.setText("");
        jLabel3.setText("");
        
        
    }
    
    public RecipePreviewPanel(Recipe recipe){
        initComponents();
        currentRecipe = recipe;
        //jLabelRecipePreviewImg.setIcon(recipe.getImageFromRes(recipe));
        DetailsForm df = new DetailsForm();
        df.setVisible(false);
        
        jLabelRecipePreviewImg.setIcon(df.sendImg(recipe));
        jLabel1.setText(recipe.getName());
        //String pathh = recipe.getImageName();
        jLabel3.setText(recipe.getCookingTime());
       
        
        
        ImageIcon imageIcon = loadImageIcon(recipe.getImageName());
        //jLabelRecipePreviewImg.setIcon(imageIcon);
        
    }
    
        private ImageIcon loadImageIcon(String imageName) {
        // Use the class loader to get the URL of the resource
        ClassLoader classLoader = getClass().getClassLoader();
        URL imageUrl = classLoader.getResource("resources/" + imageName);

        // Check if the resource was found
        if (imageUrl == null) {
            throw new RuntimeException("Resource not found: resources/" + imageName);
        }

        // Create and return an ImageIcon from the URL
        return new ImageIcon(imageUrl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelRecipePreviewImg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(620, 180));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(620, 180));

        jButton3.setText("Редактирай");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Изтрий");
        jButton4.setMaximumSize(new java.awt.Dimension(93, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(93, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(93, 23));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton7.setText("Детайли");
        jButton7.setMaximumSize(new java.awt.Dimension(93, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(93, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(93, 23));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabelRecipePreviewImg.setMaximumSize(new java.awt.Dimension(210, 144));
        jLabelRecipePreviewImg.setMinimumSize(new java.awt.Dimension(210, 144));
        jLabelRecipePreviewImg.setPreferredSize(new java.awt.Dimension(210, 144));

        jLabel2.setText("Време за приготвяне:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelRecipePreviewImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 44, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(21, 21, 21)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRecipePreviewImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            // TODO add your handling code here:
            EditRecipe er = new EditRecipe(currentRecipe);
            er.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            recipeService.deleteRecipe(currentRecipe);
        } catch (SQLException ex) {
            Logger.getLogger(RecipePreviewPanel.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            // TODO add your handling code here:
            recipeService.showDetails(currentRecipe);
        } catch (SQLException ex) {
            Logger.getLogger(RecipePreviewPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelRecipePreviewImg;
    // End of variables declaration//GEN-END:variables
}
